{% set name = "cfn-lint" %}
{% set version = "1.41.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws-cloudformation/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 43fc070bad4b84688f269a9a34b8ea02f97b0ce47b70d8cfc5b203b6b9710a17

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - cfn-lint = cfnlint.runner:main

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
  run:
    - python
    - pyyaml >5.4
    - aws-sam-translator >=1.97.0
    - jsonpatch
    - networkx >=2.4,<4
    - sympy >=1.0.0
    - regex
    - typing_extensions
  run_constrained:
    - junit-xml >=1.9,<2.0
    - jschema-to-python >=1.2.3,<1.3.0
    - sarif_om >=1.0.4,<1.1.0

# Test relies on being in a git repo folder.
# [Optional] Skip long tests. Remove/comment-out to test all

{% set ignore_tests = "" %}
{% set ignore_tests = ignore_tests + " --deselect=test/unit/module/maintenance/test_update_documentation.py::TestUpdateDocumentation::test_update_docs" %}
{% set ignore_tests = ignore_tests + " -m \"not data\"" %}

test:
  source_files:
    - test
    - src/cfnlint/rules  # Used by some tests
  imports:
    - cfnlint
  commands:
    - cfn-lint -h
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv {{ ignore_tests }} test
  requires:
    - pip
    - pytest
    - defusedxml
    - pydot
    - junit-xml >=1.9,<2.0
    - sarif_om >=1.0.4,<1.1.0
    - jschema-to-python >=1.2.3,<1.3.0

about:
  home: https://github.com/aws-cloudformation/cfn-lint
  license: MIT-0
  license_family: MIT
  license_file: LICENSE
  summary: CloudFormation Linter
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-lint/tree/main/docs/getting_started
  dev_url: https://github.com/aws-cloudformation/cfn-lint

extra:
  recipe-maintainers:
    - hajapy
