{% set name = "cfn-lint" %}
{% set version = "0.86.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7216e9c10dd27af73821d0ae79b17406cd89f5dfbc25feb5d2ba756eb6e9a651

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  entry_points:
    - cfn-lint = cfnlint.__main__:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - pyyaml <=5.2                  # [py==34]
    - pyyaml <=5.4                  # [py==35]
    - pyyaml >5.4
    - networkx >=2.4,<4
    - aws-sam-translator >=1.86.0
    - jsonpatch
    - jsonschema >=3.0,<5
    - junit-xml ~=1.9
    - sympy >=1.0.0
    - regex >=2021.7.1
    - sarif_om ~=1.0.4
    - jschema-to-python ~=1.2.3
    

test:
  requires:
    - pip
    - junit-xml
    - importlib_resources
  imports:
    - cfnlint
  commands:
    - cfn-lint -h
    - pip check

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  license: MIT-0
  license_family: MIT
  license_file: LICENSE
  summary: 'CloudFormation Linter'
  description: |
    Validate CloudFormation yaml/json templates against the 
    CloudFormation spec and additional checks. Includes checking 
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint

extra:
  recipe-maintainers:
    - hajapy
