{% set name = "cfn-lint" %}
{% set version = "1.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws-cloudformation/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2d7285b2347f3fefd2445e09321a42d083957c1d2edaf496ccd242e2813ba389

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]
  entry_points:
    - cfn-lint = cfnlint.runner:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.3
  run:
    - python
    - pyyaml >5.4
    - aws-sam-translator >=1.97.0
    - jsonpatch
    - networkx >=2.4,<4
    - sympy >=1.0.0
    - regex >=2021.7.1
    - typing_extensions
  run_constrained:
    - junit-xml ~=1.9
    - sarif_om ~=1.0.4
    - jschema-to-python ~=1.2.3

test:
  requires:
    - pip
  imports:
    - cfnlint
  commands:
    - cfn-lint -h
    - pip check

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  license: MIT-0
  license_family: MIT
  license_file: LICENSE
  summary: 'CloudFormation Linter'
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint

extra:
  recipe-maintainers:
    - hajapy
