{% set name = "cfn-lint" %}
{% set version = "1.56.3" %}
{% set ignore_tests = "" %}
{% set ignore_tests = 'ignore_tests + " --deselect=test/unit/module/maintenance/test_update_documentation.py::TestUpdateDocumentation::test_update_docs"' %}
{% set ignore_tests = 'ignore_tests + " --deselect=test/unit/module/formatters/test_formatters.py::TestFormatters::test_sarif_formatter"' %}
{% set ignore_tests = ignore_tests + " --ignore=test/integration" %}

# Test relies on being in a git repo folder.
# [Optional] Skip long tests. Remove/comment-out to test all
# ImportError: Missing optional dependencies sarif
# not possible to run in Anaconda environment, even with cfn-lint -u
# =========================== short test summary info ============================
# ERROR test/integration - pytest.UsageError: Full schemas not available. Run 'cfn-lint -u' before running integration tests.
# !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/aws-cloudformation/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee3c796bfac8a0623ad17bbead8e27666e4d762d691fc569cc73fc9e713ea410

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - cfn-lint = cfnlint.runner:main
  skip: true  # [py<310 and py>314]

requirements:
  host:
    - pip
    - python
    - setuptools >=80.10.2
  run:
    - python
    - pyyaml >=6.0.3
    - jsonpatch
    - networkx >=2.4,<4
    - sympy >=1.14.0
    - regex
    - typing_extensions
  run_constrained:
    - junit-xml >=1.9,<2.0
    - jschema-to-python >=1.2.3,<1.3.0
    - sarif_om >=1.0.4,<1.1.0

test:
  source_files:
    - test
    - src/cfnlint/rules  # Used by some tests
    - scripts  # needed by test_update_specs_from_pricing
  imports:
    - cfnlint
    - cfnlint.data
  commands:
    - cfn-lint -h
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m pytest -vv {{ ignore_tests }} -m "not data" test
  requires:
    - pip
    - pytest
    - defusedxml
    - pydot
    - junit-xml >=1.9,<2.0
    - sarif_om >=1.0.4,<1.1.0
    - jschema-to-python >=1.2.3,<1.3.0
    # Imported by scripts/update_specs_from_pricing.py
    - boto3

about:
  home: https://github.com/aws-cloudformation/cfn-lint
  license: MIT-0
  license_family: MIT
  license_file: LICENSE
  summary: CloudFormation Linter
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-lint/tree/main/docs/getting_started
  dev_url: https://github.com/aws-cloudformation/cfn-lint

extra:
  recipe-maintainers:
    - hajapy
