{% set name = "cfn-lint" %}
{% set version = "0.48.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9d07ec844fa3892399af9aef3cf6de22f725c004dd24ac54bae41659fddc874

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cfn-lint = cfnlint.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml <=5.2                  # [py==34]
    - pyyaml                        # [py!=34]
    - networkx ~=2.4                # [py>=35]
    - networkx <=2.2                # [py<35]
    - six >=1.11
    - aws-sam-translator >=1.34.0
    - jsonpatch                     # [py!=34]
    - jsonpatch  <=1.24             # [py==34]
    - jsonschema ~=3.0
    - setuptools
    - pathlib2 >=2.3.0              # [py<=34]
    - importlib_resources ~=1.0.2   # [py==34]
    - importlib_resources >=1.4,<4  # [py<37 and py!=34]
    - junit-xml ~=1.9
    - pyrsistent <=0.16.0           # [py<35]

test:
  requires:
    - junit-xml
    - importlib_resources
  imports:
    - cfnlint
  commands:
    - cfn-lint -h

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  license: MIT No Attribution
  license_family: MIT
  license_file: LICENSE
  summary: 'CloudFormation Linter'
  description: |
    Validate CloudFormation yaml/json templates against the 
    CloudFormation spec and additional checks. Includes checking 
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint

extra:
  recipe-maintainers:
    - hajapy
