{% set name = "cfn-lint" %}
{% set version = "1.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws-cloudformation/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2d7285b2347f3fefd2445e09321a42d083957c1d2edaf496ccd242e2813ba389

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]
  entry_points:
    - cfn-lint = cfnlint.runner:main

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - wheel
  run:
    - python
    - pyyaml >5.4
    - aws-sam-translator >=1.97.0
    - jsonpatch
    - networkx >=2.4,<4
    - sympy >=1.0.0
    - regex
    - typing_extensions
  run_constrained:
    - junit-xml >=1.9,<2
    - jschema-to-python >=1.2.3,<1.3
    - sarif-om >=1.0.4,<1.1

# ModuleNotFoundError: No module named 'sarif_om'
{% set tests_to_skip = "test_sarif_formatter" %}
# subprocess.CalledProcessError: Command '['git', 'grep', '-l', 'id = "E0000"', 'src/cfnlint/rules/']' returned non-zero exit status 128.
{% set tests_to_skip = tests_to_skip + " or test_update_docs" %}

test:
  source_files:
    - test
    - src/cfnlint/rules
  requires:
    - pip
    - pytest
    - defusedxml
    - junit-xml
    - pydot
  imports:
    - cfnlint
    - cfnlint.api
    - cfnlint.conditions
    - cfnlint.config
    - cfnlint.core
    - cfnlint.data
    - cfnlint.context
    - cfnlint.decode
    - cfnlint.exceptions
    - cfnlint.formatters
    - cfnlint.graph
    - cfnlint.helpers
    - cfnlint.jsonschema
    - cfnlint.maintenance
    - cfnlint.match
    - cfnlint.rules
    - cfnlint.runner
    - cfnlint.schema
    - cfnlint.template
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v -k "not ({{ tests_to_skip }})" test
    - cfn-lint -h

about:
  home: https://github.com/aws-cloudformation/cfn-python-lint
  license: MIT-0
  license_family: MIT
  license_file: LICENSE
  summary: CloudFormation Linter
  description: |
    Validate CloudFormation yaml/json templates against the
    CloudFormation spec and additional checks. Includes checking
    valid values for resource properties and best practices.
  doc_url: https://github.com/aws-cloudformation/cfn-python-lint/tree/master/docs
  dev_url: https://github.com/aws-cloudformation/cfn-python-lint

extra:
  recipe-maintainers:
    - hajapy